# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  #- pip install -U tox-travis
  - pip install coveralls
  - pip install setup.py install

before install:

  - pip install coverage
  - pip install matplotlib
  - pip install scipy
  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib

script: 
  - coverage run --source=final_project/final_project.py setup.py test
  - coverage report -m

after_success: coveralls
#language: python
#python: 2.7

